### PR TITLE
pass ZT_OFFICIAL_RELEASE=1 into build

### PR DESCRIPTION
**Pull request by sfc-gh-dwu**
Set flag ZT_OFFICIAL_RELEASE=1 during compilation

### CODE REVIEW

**Comment by henrist** [comment]
Can you explain the reasoning behind adding this flag?

As far as I can see, this is related to an actual official release. Since we build from source it will never be an "official release" in that sense.

Also - this flag is only used if compiling under Mac or NetBSD, neither of which we are doing.

**Comment by diwu1989** [comment]
It also changes some compile flags on linux:
https://github.com/zerotier/ZeroTierOne/blob/master/make-linux.mk#L267-L270

We're not building official release but the binary compiled for the image should be as close to the official binary as possible in my opinion. Otherwise, if there are any bugs related to the image's compile flags, it will be difficult to discern if it is due to product behavior or the specific way this image was built.

**Comment by diwu1989** [comment]
Oops, it was a typo, I think this should be `ZT_OFFICIAL`

**Comment by henrist** [comment]
I see! The `ZT_OFFICIAL` flag seems to provide compatibility to older runtimes. Since we run in Docker the runtime is already given and support for other runtimes I think should be out of scope.

**Pull request closed without merging**
